# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-04 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_honeypot', '0002_auto_20160208_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='password'),
        ),
    ]
